### ISSUE TITLE
com.hierynomus.mssmb2.SMBApiException - STATUS_OBJECT_NAME_NOT_FOUND(3221225524/3221225524): Create failed for ConsumeFile

### ISSUE THREAD

**Issue by sudhilmishra** [jborza/camel-smbj#2]
2018-05-01 20:33:34 INFO  Connection:184 - Successfully authenticated test on ***.168.16.**, session is 123548760801333
2018-05-01 20:33:34 INFO  Session:146 - Connecting to \\***.168.16.**\ConsumeFile on session 123548760801333
2018-05-01 20:33:34 INFO  Session:208 - Logging off session 123548760801333 from host ***.168.16.**
2018-05-01 20:33:34 WARN  SmbConsumer:213 - Consumer Consumer[smb2://Domain;test@***.168.16.**/claim?delete=true&password=xxxxxx] failed polling endpoint: smb2://Domain;test@***.168.16.**/ConsumeFile?delete=true&password=xxxxxx. Will try again at next poll. Caused by: [com.hierynomus.mssmb2.SMBApiException - STATUS_OBJECT_NAME_NOT_FOUND(3221225524/3221225524): Create failed for ConsumeFile]
com.hierynomus.mssmb2.SMBApiException: STATUS_OBJECT_NAME_NOT_FOUND(3221225524/3221225524): Create failed for ConsumeFile
	at com.hierynomus.smbj.share.Share.receive(Share.java:342)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:322)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:135)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:79)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:69)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:126)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:213)
	at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:186)
	at com.github.jborza.camel.component.smbj.SmbShare.listFiles(SmbShare.java:175)
	at com.github.jborza.camel.component.smbj.SmbClient.listFiles(SmbClient.java:39)
	at com.github.jborza.camel.component.smbj.SmbOperations.listFiles(SmbOperations.java:212)
	at com.github.jborza.camel.component.smbj.SmbConsumer.pollDirectory(SmbConsumer.java:48)
	at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:124)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jborza** [comment]
Hi,
Try setting &dfs=true in the route URL. If you're consuming from Windows Servers and they use DFS and it's not enabled, you'll be getting STATUS_OBJECT_NAME_NOT_FOUND as in your listing.

**Comment by jborza** [comment]
Hi @sudhilmishra - can I close the issue?

**Comment by sudhilmishra** [comment]
Hi @jborza , Yes please close the issue, &dfs=true , worked fine, thank you.

**Comment by jayaram141290** [comment]
Hi,

I have a same error but we have configured regular share..no DFS..any suggestion?
