### ISSUE TITLE
SmbProducer is not compatible with camel 3.8.0

### ISSUE THREAD

**Issue by jvanderwood** [jborza/camel-smbj#27]
The immediate problem is it references "log" in superclass GenericFileProducer.  In the latest camel, the logger is names "LOG" and it's private.
I don't know what other issue may exist.
I will probably have to stop using this library if this can't be fixed.  Thanks.

**Comment by ondrejbilek** [comment]
Same here. I get exception once the app hits line with "log" in it,
`java.lang.NoSuchFieldError: log
	at com.github.jborza.camel.component.smbj.SmbConsumer.doStart(SmbConsumer.java:111) ~[camel-smbj-0.2.22.jar:na]
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119) ~[camel-api-3.11.1.jar:3.11.1]
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113) ~[camel-api-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3464) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRouteConsumers(InternalRouteStartupManager.java:401) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartRouteConsumers(InternalRouteStartupManager.java:319) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:213) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:147) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3167) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2847) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2798) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.spring.boot.SpringBootCamelContext.doStart(SpringBootCamelContext.java:43) ~[camel-spring-boot-3.11.1.jar:3.11.1]
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119) ~[camel-api-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2494) ~[camel-base-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:245) ~[camel-core-engine-3.11.1.jar:3.11.1]
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:119) ~[camel-spring-3.11.1.jar:3.11.1]
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:151) ~[camel-spring-3.11.1.jar:3.11.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.3.jar:2.5.3]
	at cz.heimstaden.czechesb.CzechEsbApplication.main(CzechEsbApplication.java:17) [classes/:na]`
